spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://postgres.railway.internal:5432/railway
        username: postgres
        password: KHEfnhCdurPZdhjuhGrQWEuhincUAPxl
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create
        show-sql: true
    sql:
        init:
            platform: postgres