spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
        username: ${PGUSER}
        password: ${PGPASSWORD}
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create
        show-sql: true
    sql:
        init:
            platform: postgres